misc:
  dataset: geolife
  # 315 known locations, ranging from 2 to 316. 1 reserved for unknow locations
  total_loc_num: 298
  # 29 users, ranging from 1 to 29
  total_user_num: 30
  if_embed_poi: False
  # 
  if_embed_user: True
  if_embed_time: False
  if_embed_weekday: False
  if_embed_duration: False
  
  # how many days in the past we consider
  previous_day: 7
  verbose: False
  debug: False
  batch_size: 128
  print_step: 10

embedding:
  loc_emb_size: 32
  time_emb_size: 12
  weekday_emb_size: 4
  user_emb_size: 16
  duration_emb_size: 16

model:
  networkName: rnn
  # only for LSTM: LSTM or GRU
  attention: False
  rnn_type: LSTM
  hidden_size: 128


optimiser:
  optimizer: Adam
  max_epoch: 100
  lr: 0.001
  weight_decay: 0.001
  # lr: 0.01
  # for Adam
  beta1: 0.9
  beta2: 0.999
  # for SGD
  momentum: 0.98
  # for warmup
  num_warmup_epochs: 3
  num_training_epochs: 50
  # for decay
  patience: 3
  lr_step_size: 1
  lr_gamma: 0.1

dataset:
  source_root: ./data/