misc:
  dataset: gc
  # 9875 known locations, ranging from 2 to 9876
  # 0 reserved for padding, 1 reserved for unknown
  total_loc_num: 9877
  # 93 users, ranging from 1 to 93
  # 1 reserved for unknown
  total_user_num: 94

  # 
  if_embed_user: True
  if_embed_time: True
  if_embed_mode: False
  # loss
  if_loss_mode: False
  
  # how many days in the past we consider
  previous_day: 7
  verbose: False
  debug: False
  batch_size: 256
  print_step: 10
  

embedding:
  # also size for time and mode
  base_emb_size: 64
  # user_embedding added at the end 
  user_emb_size: 16

model:
  networkName: deepmove
  # only for LSTM: LSTM or GRU
  attention: False
  rnn_type: LSTM
  hidden_size: 64
  fc_dropout: 0.1


optimiser:
  optimizer: Adam
  max_epoch: 100
  lr: 0.001
  weight_decay: 0.00001
  # lr: 0.01
  # for Adam
  beta1: 0.9
  beta2: 0.999
  # for SGD
  momentum: 0.98
  # for warmup
  num_warmup_epochs: 2
  num_training_epochs: 50
  # for decay
  patience: 3
  lr_step_size: 1
  lr_gamma: 0.1

dataset:
  source_root: ./data/