misc:
  dataset: gc
  # 2204 known locations, ranging from 2 to 2205
  total_loc_num: 2206
  # 93 users, ranging from 1 to 93
  total_user_num: 94

  # 
  if_embed_user: True
  if_embed_time: True
  
  # how many days in the past we consider
  previous_day: 7
  verbose: False
  debug: False
  batch_size: 256
  print_step: 10
  

embedding:
  loc_emb_size: 32
  time_emb_size: 32
  user_emb_size: 32

model:
  networkName: deepmove
  # only for LSTM: LSTM or GRU
  # attention: False
  rnn_type: GRU
  hidden_size: 96
  # only for transformer
  # num_encoder_layers: 6
  # nhead: 4
  # dim_feedforward: 256
  # dropout: 0.1


optimiser:
  optimizer: Adam
  max_epoch: 100
  lr: 0.001
  weight_decay: 0.00001
  # lr: 0.01
  # for Adam
  beta1: 0.9
  beta2: 0.999
  # for SGD
  momentum: 0.98
  # for warmup
  num_warmup_epochs: 3
  num_training_epochs: 50
  # for decay
  patience: 3
  lr_step_size: 1
  lr_gamma: 0.1

dataset:
  source_root: ./data/